//
// Info.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Info: Codable {

    public var count: Int?
    public var pages: Int?

    public init(count: Int?, pages: Int?) {
        self.count = count
        self.pages = pages
    }


}

